export const repostories = {
    'airbnb-clone': {
        tags: ['fullStack'],
        coverImageUrl: './images/airbnb-clone/img-1.png',
        keyFeatures: ['desc-1', 'desc-2', 'desc-3', 'desc-4', 'desc-5', 'desc-6', 'desc-7', 'desc-8', 'desc-9'],
        snapshots: [
            { id: 1, desc: 'desc-1', imageUrl: './images/airbnb-clone/img-1.png' },
            { id: 2, desc: 'desc-2', imageUrl: './images/airbnb-clone/img-2.png' },
            { id: 3, desc: 'desc-3', imageUrl: './images/airbnb-clone/img-3.png' },
            { id: 4, desc: 'desc-4', imageUrl: './images/airbnb-clone/img-4.png' },
            { id: 5, desc: 'desc-5', imageUrl: './images/airbnb-clone/img-5.png' },
            { id: 6, desc: 'desc-6', imageUrl: './images/airbnb-clone/img-6.png' },
            { id: 7, desc: 'desc-7', imageUrl: './images/airbnb-clone/img-7.png' },
            { id: 8, desc: 'desc-8', imageUrl: './images/airbnb-clone/img-8.png' },
            { id: 9, desc: 'desc-9', imageUrl: './images/airbnb-clone/img-9.png' },
            { id: 10, desc: 'desc-10', imageUrl: './images/airbnb-clone/img-10.png' },
            { id: 11, desc: 'desc-11', imageUrl: './images/airbnb-clone/img-11.png' },
            { id: 12, desc: 'desc-12', imageUrl: './images/airbnb-clone/img-12.png' },
        ],
        techStacks: ['next-js', 'typescript', 'tailwindcss', 'prisma', 'mongodb'],
        webDevToolkits: [
            { id: 'nextauth-js', name: 'NextAuth.js', desc: 'nextauth-desc' },
            { id: 'next-cloudinary', name: 'Next Cloudinary', desc: 'next-cloudinary-desc' },
            { id: 'zustand', name: 'Zustand', desc: 'zustand-desc' },
        ],
    },
    'trello-clone': {
        tags: ['fullStack'],
        coverImageUrl: './images/trello-clone/img-1.png',
        keyFeatures: ['desc-1', 'desc-2', 'desc-3', 'desc-4', 'desc-5', 'desc-6', 'desc-7', 'desc-8'],
        snapshots: [
            { id: 1, desc: 'desc-1', imageUrl: './images/trello-clone/img-1.png' },
            { id: 2, desc: 'desc-2', imageUrl: './images/trello-clone/img-2.png' },
            { id: 3, desc: 'desc-3', imageUrl: './images/trello-clone/img-3.png' },
            { id: 4, desc: 'desc-4', imageUrl: './images/trello-clone/img-4.png' },
            { id: 5, desc: 'desc-5', imageUrl: './images/trello-clone/img-5.png' },
            { id: 6, desc: 'desc-6', imageUrl: './images/trello-clone/img-6.png' },
            { id: 7, desc: 'desc-7', imageUrl: './images/trello-clone/img-7.png' },
            { id: 8, desc: 'desc-8', imageUrl: './images/trello-clone/img-8.png' },
            { id: 9, desc: 'desc-9', imageUrl: './images/trello-clone/img-9.png' },
            { id: 10, desc: 'desc-10', imageUrl: './images/trello-clone/img-10.png' },
            { id: 11, desc: 'desc-11', imageUrl: './images/trello-clone/img-11.png' },
        ],
        techStacks: ['next-js', 'typescript', 'tailwindcss', 'prisma', 'mysql'],
        webDevToolkits: [
            { id: 'clerk', name: 'Clerk', desc: 'clerk-desc' },
            { id: 'planetscale', name: 'Planetscale', desc: 'planetscale-desc' },
            { id: 'shadcn', name: 'Shadcn', desc: 'shadcn-desc' },
            { id: 'stripe', name: 'Stripe', desc: 'stripe-desc' },
            { id: 'tanstack', name: 'Tanstack', desc: 'tanstack-desc' },
            { id: 'unsplash', name: 'Unsplash', desc: 'unsplash-desc' },
            { id: 'zod', name: 'Zod', desc: 'zod-desc' },
            { id: 'zustand', name: 'Zustand', desc: 'zustand-desc' },
        ],
    },
    'spotify-clone': {
        tags: ['fullStack'],
        coverImageUrl: './images/spotify-clone/img-1.png',
        keyFeatures: ['desc-1', 'desc-2', 'desc-3', 'desc-4', 'desc-5', 'desc-6', 'desc-7'],
        snapshots: [
            { id: 1, desc: 'desc-1', imageUrl: './images/spotify-clone/img-1.png' },
            { id: 2, desc: 'desc-2', imageUrl: './images/spotify-clone/img-2.png' },
            { id: 3, desc: 'desc-3', imageUrl: './images/spotify-clone/img-3.png' },
            { id: 4, desc: 'desc-4', imageUrl: './images/spotify-clone/img-4.png' },
            { id: 5, desc: 'desc-5', imageUrl: './images/spotify-clone/img-5.png' },
            { id: 6, desc: 'desc-6', imageUrl: './images/spotify-clone/img-6.png' },
            { id: 7, desc: 'desc-7', imageUrl: './images/spotify-clone/img-7.png' },
        ],
        techStacks: ['next-js', 'typescript', 'tailwindcss', 'postgresql'],
        webDevToolkits: [
            { id: 'zustand', name: 'Zustand', desc: 'zustand-desc' },
            { id: 'supabase', name: 'Supabase', desc: 'supabase-desc' },
            { id: 'stripe', name: 'Stripe', desc: 'stripe-desc' },
        ],
    },
    'github-issues-clone': {
        tags: ['frontend'],
        coverImageUrl: './images/github-issues-clone/img-1.png',
        snapshots: [
            { id: 1, desc: 'desc-1', imageUrl: './images/github-issues-clone/img-1.png' },
            { id: 2, desc: 'desc-2', imageUrl: './images/github-issues-clone/img-2.png' },
            { id: 3, desc: 'desc-3', imageUrl: './images/github-issues-clone/img-3.png' },
            { id: 4, desc: 'desc-4', imageUrl: './images/github-issues-clone/img-4.png' },
            { id: 5, desc: 'desc-5', imageUrl: './images/github-issues-clone/img-5.png' },
            { id: 6, desc: 'desc-6', imageUrl: './images/github-issues-clone/img-6.png' },
            { id: 7, desc: 'desc-7', imageUrl: './images/github-issues-clone/img-7.png' },
            { id: 8, desc: 'desc-8', imageUrl: './images/spotgithub-issuesify-clone/img-8.png' },
            { id: 9, desc: 'desc-9', imageUrl: './images/github-issues-clone/img-9.png' },
        ],
        keyFeatures: ['desc-1', 'desc-2', 'desc-3', 'desc-4', 'desc-5', 'desc-6', 'desc-7', 'desc-8'],
        techStacks: ['react-js', 'typescript', 'styled-components', 'redux', 'firebase'],
        webDevToolkits: [
            { id: 'storybook', name: 'StoryBook', desc: 'storybook-desc' },
            { id: 'supabase', name: 'Supabase', desc: 'supabase-desc' },
        ],
    },
};
